version: '3'
services:
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testDB
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4848:4848"
    links:
      - db